-- local data = BlackMarketTweakData._init_projectiles
-- function BlackMarketTweakData:_init_projectiles(tweak_data, ...)
	-- data(self, tweak_data, ...)
	-- self.projectiles.concussion = {
		-- name_id = "bm_concussion",
		-- unit = "units/pd2_crimefest_2016/fez1/weapons/wpn_fps_gre_pressure/wpn_third_gre_pressure",
		-- unit_dummy = "units/pd2_crimefest_2016/fez1/weapons/wpn_fps_gre_pressure/wpn_fps_gre_pressure_husk",
		-- sprint_unit = "units/pd2_crimefest_2016/fez1/weapons/wpn_fps_gre_pressure/wpn_third_gre_pressure_sprint",
		-- icon = "concussion_grenade",
		-- throwable = true,
		-- max_amount = 6,
		-- animation = "throw_concussion",
		-- anim_global_param = "projectile_frag",
		-- texture_bundle_folder = "fez1",
		-- throw_allowed_expire_t = 0.1,
		-- expire_t = 0.1,
		-- repeat_expire_t = 0.1,
		-- is_a_grenade = true,
		-- impact_detonation = true
	-- }
	-- -- local tweak_entry = tweak_data.blackmarket.projectiles["concussion"]
					-- -- tweak_entry.throw_allowed_expire_t = 0.01
					-- -- tweak_entry.expire_t = 0.01
					-- -- tweak_entry.repeat_expire_t = 0.01
					-- -- tweak_entry.impact_detonation = true
-- end